NSE_STOCKS = [
    # === BANKING ===
    {"symbol": "HDFCBANK", "name": "HDFC Bank Ltd", "sector": "Banking"},
    {"symbol": "ICICIBANK", "name": "ICICI Bank Ltd", "sector": "Banking"},
    {"symbol": "SBIN", "name": "State Bank of India", "sector": "Banking"},
    {"symbol": "KOTAKBANK", "name": "Kotak Mahindra Bank Ltd", "sector": "Banking"},
    {"symbol": "AXISBANK", "name": "Axis Bank Ltd", "sector": "Banking"},
    {"symbol": "INDUSINDBK", "name": "IndusInd Bank Ltd", "sector": "Banking"},
    {"symbol": "BANDHANBNK", "name": "Bandhan Bank Ltd", "sector": "Banking"},
    {"symbol": "FEDERALBNK", "name": "Federal Bank Ltd", "sector": "Banking"},
    {"symbol": "IDFCFIRSTB", "name": "IDFC First Bank Ltd", "sector": "Banking"},
    {"symbol": "CANBK", "name": "Canara Bank", "sector": "Banking"},
    {"symbol": "PNB", "name": "Punjab National Bank", "sector": "Banking"},
    {"symbol": "BANKBARODA", "name": "Bank of Baroda", "sector": "Banking"},
    {"symbol": "UNIONBANK", "name": "Union Bank of India", "sector": "Banking"},
    {"symbol": "AUBANK", "name": "AU Small Finance Bank Ltd", "sector": "Banking"},
    {"symbol": "RBLBANK", "name": "RBL Bank Ltd", "sector": "Banking"},
    {"symbol": "YESBANK", "name": "Yes Bank Ltd", "sector": "Banking"},
    {"symbol": "KARURVYSYA", "name": "Karur Vysya Bank Ltd", "sector": "Banking"},
    {"symbol": "DCBBANK", "name": "DCB Bank Ltd", "sector": "Banking"},
    {"symbol": "SOUTHBANK", "name": "South Indian Bank Ltd", "sector": "Banking"},
    # === FINANCE / NBFC ===
    {"symbol": "BAJFINANCE", "name": "Bajaj Finance Ltd", "sector": "Finance"},
    {"symbol": "BAJAJFINSV", "name": "Bajaj Finserv Ltd", "sector": "Finance"},
    {"symbol": "CHOLAFIN", "name": "Cholamandalam Investment & Finance Co Ltd", "sector": "Finance"},
    {"symbol": "MUTHOOTFIN", "name": "Muthoot Finance Ltd", "sector": "Finance"},
    {"symbol": "MANAPPURAM", "name": "Manappuram Finance Ltd", "sector": "Finance"},
    {"symbol": "LICHSGFIN", "name": "LIC Housing Finance Ltd", "sector": "Finance"},
    {"symbol": "M&MFIN", "name": "Mahindra & Mahindra Financial Services Ltd", "sector": "Finance"},
    {"symbol": "SHRIRAMFIN", "name": "Shriram Finance Ltd", "sector": "Finance"},
    {"symbol": "SUNDARMFIN", "name": "Sundaram Finance Ltd", "sector": "Finance"},
    {"symbol": "PNBHOUSING", "name": "PNB Housing Finance Ltd", "sector": "Finance"},
    {"symbol": "AAVAS", "name": "Aavas Financiers Ltd", "sector": "Finance"},
    {"symbol": "IRFC", "name": "Indian Railway Finance Corp Ltd", "sector": "Finance"},
    {"symbol": "PFC", "name": "Power Finance Corporation Ltd", "sector": "Finance"},
    {"symbol": "RECLTD", "name": "REC Ltd", "sector": "Finance"},
    {"symbol": "CRISIL", "name": "CRISIL Ltd", "sector": "Finance"},
    {"symbol": "CDSL", "name": "Central Depository Services (India) Ltd", "sector": "Finance"},
    {"symbol": "BSE", "name": "BSE Ltd", "sector": "Finance"},
    {"symbol": "MCX", "name": "Multi Commodity Exchange of India Ltd", "sector": "Finance"},
    {"symbol": "ANGELONE", "name": "Angel One Ltd", "sector": "Finance"},
    {"symbol": "MOTILALOFS", "name": "Motilal Oswal Financial Services Ltd", "sector": "Finance"},
    # === INSURANCE ===
    {"symbol": "HDFCLIFE", "name": "HDFC Life Insurance Co Ltd", "sector": "Insurance"},
    {"symbol": "SBILIFE", "name": "SBI Life Insurance Co Ltd", "sector": "Insurance"},
    {"symbol": "ICICIPRULI", "name": "ICICI Prudential Life Insurance Co Ltd", "sector": "Insurance"},
    {"symbol": "LICI", "name": "Life Insurance Corporation of India", "sector": "Insurance"},
    {"symbol": "STARHEALTH", "name": "Star Health and Allied Insurance Co Ltd", "sector": "Insurance"},
    {"symbol": "NIACL", "name": "New India Assurance Co Ltd", "sector": "Insurance"},
    {"symbol": "GICRE", "name": "General Insurance Corporation of India", "sector": "Insurance"},
    # === IT & TECHNOLOGY ===
    {"symbol": "TCS", "name": "Tata Consultancy Services Ltd", "sector": "IT"},
    {"symbol": "INFY", "name": "Infosys Ltd", "sector": "IT"},
    {"symbol": "WIPRO", "name": "Wipro Ltd", "sector": "IT"},
    {"symbol": "HCLTECH", "name": "HCL Technologies Ltd", "sector": "IT"},
    {"symbol": "TECHM", "name": "Tech Mahindra Ltd", "sector": "IT"},
    {"symbol": "MPHASIS", "name": "Mphasis Ltd", "sector": "IT"},
    {"symbol": "LTTS", "name": "L&T Technology Services Ltd", "sector": "IT"},
    {"symbol": "COFORGE", "name": "Coforge Ltd", "sector": "IT"},
    {"symbol": "PERSISTENT", "name": "Persistent Systems Ltd", "sector": "IT"},
    {"symbol": "KPITTECH", "name": "KPIT Technologies Ltd", "sector": "IT"},
    {"symbol": "OFSS", "name": "Oracle Financial Services Software Ltd", "sector": "IT"},
    {"symbol": "LTIM", "name": "LTIMindtree Ltd", "sector": "IT"},
    {"symbol": "TATAELXSI", "name": "Tata Elxsi Ltd", "sector": "IT"},
    {"symbol": "CYIENT", "name": "Cyient Ltd", "sector": "IT"},
    {"symbol": "ZENSAR", "name": "Zensar Technologies Ltd", "sector": "IT"},
    {"symbol": "MASTEK", "name": "Mastek Ltd", "sector": "IT"},
    {"symbol": "NAUKRI", "name": "Info Edge (India) Ltd", "sector": "IT"},
    {"symbol": "INDIAMART", "name": "IndiaMART InterMESH Ltd", "sector": "IT"},
    # === ENERGY & OIL/GAS ===
    {"symbol": "RELIANCE", "name": "Reliance Industries Ltd", "sector": "Energy"},
    {"symbol": "ONGC", "name": "Oil & Natural Gas Corporation Ltd", "sector": "Energy"},
    {"symbol": "BPCL", "name": "Bharat Petroleum Corporation Ltd", "sector": "Energy"},
    {"symbol": "IOC", "name": "Indian Oil Corporation Ltd", "sector": "Energy"},
    {"symbol": "HINDPETRO", "name": "Hindustan Petroleum Corporation Ltd", "sector": "Energy"},
    {"symbol": "GAIL", "name": "GAIL (India) Ltd", "sector": "Energy"},
    {"symbol": "PETRONET", "name": "Petronet LNG Ltd", "sector": "Energy"},
    {"symbol": "OIL", "name": "Oil India Ltd", "sector": "Energy"},
    {"symbol": "MGL", "name": "Mahanagar Gas Ltd", "sector": "Energy"},
    {"symbol": "IGL", "name": "Indraprastha Gas Ltd", "sector": "Energy"},
    {"symbol": "GUJGASLTD", "name": "Gujarat Gas Ltd", "sector": "Energy"},
    # === POWER ===
    {"symbol": "TATAPOWER", "name": "Tata Power Co Ltd", "sector": "Power"},
    {"symbol": "ADANIPOWER", "name": "Adani Power Ltd", "sector": "Power"},
    {"symbol": "ADANIGREEN", "name": "Adani Green Energy Ltd", "sector": "Power"},
    {"symbol": "TORNTPOWER", "name": "Torrent Power Ltd", "sector": "Power"},
    {"symbol": "NTPC", "name": "NTPC Ltd", "sector": "Power"},
    {"symbol": "POWERGRID", "name": "Power Grid Corporation of India Ltd", "sector": "Power"},
    {"symbol": "CESC", "name": "CESC Ltd", "sector": "Power"},
    {"symbol": "ADANITRANS", "name": "Adani Transmission Ltd", "sector": "Power"},
    # === PHARMA & HEALTHCARE ===
    {"symbol": "SUNPHARMA", "name": "Sun Pharmaceutical Industries Ltd", "sector": "Pharma"},
    {"symbol": "DRREDDY", "name": "Dr Reddys Laboratories Ltd", "sector": "Pharma"},
    {"symbol": "CIPLA", "name": "Cipla Ltd", "sector": "Pharma"},
    {"symbol": "DIVISLAB", "name": "Divi's Laboratories Ltd", "sector": "Pharma"},
    {"symbol": "BIOCON", "name": "Biocon Ltd", "sector": "Pharma"},
    {"symbol": "LUPIN", "name": "Lupin Ltd", "sector": "Pharma"},
    {"symbol": "AUROPHARMA", "name": "Aurobindo Pharma Ltd", "sector": "Pharma"},
    {"symbol": "IPCALAB", "name": "IPCA Laboratories Ltd", "sector": "Pharma"},
    {"symbol": "TORNTPHARM", "name": "Torrent Pharmaceuticals Ltd", "sector": "Pharma"},
    {"symbol": "ALKEM", "name": "Alkem Laboratories Ltd", "sector": "Pharma"},
    {"symbol": "GRANULES", "name": "Granules India Ltd", "sector": "Pharma"},
    {"symbol": "LAURUS", "name": "Laurus Labs Ltd", "sector": "Pharma"},
    {"symbol": "NATCOPHARM", "name": "Natco Pharma Ltd", "sector": "Pharma"},
    {"symbol": "GLENMARK", "name": "Glenmark Pharmaceuticals Ltd", "sector": "Pharma"},
    {"symbol": "ABBOTINDIA", "name": "Abbott India Ltd", "sector": "Pharma"},
    {"symbol": "APOLLOHOSP", "name": "Apollo Hospitals Enterprise Ltd", "sector": "Healthcare"},
    {"symbol": "FORTIS", "name": "Fortis Healthcare Ltd", "sector": "Healthcare"},
    {"symbol": "MAXHEALTH", "name": "Max Healthcare Institute Ltd", "sector": "Healthcare"},
    {"symbol": "METROPOLIS", "name": "Metropolis Healthcare Ltd", "sector": "Healthcare"},
    {"symbol": "LALPATHLAB", "name": "Dr Lal PathLabs Ltd", "sector": "Healthcare"},
    # === AUTO & AUTO ANCILLARY ===
    {"symbol": "MARUTI", "name": "Maruti Suzuki India Ltd", "sector": "Auto"},
    {"symbol": "TATAMOTORS", "name": "Tata Motors Ltd", "sector": "Auto"},
    {"symbol": "M&M", "name": "Mahindra & Mahindra Ltd", "sector": "Auto"},
    {"symbol": "BAJAJ-AUTO", "name": "Bajaj Auto Ltd", "sector": "Auto"},
    {"symbol": "HEROMOTOCO", "name": "Hero MotoCorp Ltd", "sector": "Auto"},
    {"symbol": "EICHERMOT", "name": "Eicher Motors Ltd", "sector": "Auto"},
    {"symbol": "ASHOKLEY", "name": "Ashok Leyland Ltd", "sector": "Auto"},
    {"symbol": "TVSMOTOR", "name": "TVS Motor Company Ltd", "sector": "Auto"},
    {"symbol": "ESCORTS", "name": "Escorts Kubota Ltd", "sector": "Auto"},
    {"symbol": "MOTHERSON", "name": "Samvardhana Motherson International Ltd", "sector": "Auto Ancillary"},
    {"symbol": "BOSCHLTD", "name": "Bosch Ltd", "sector": "Auto Ancillary"},
    {"symbol": "EXIDEIND", "name": "Exide Industries Ltd", "sector": "Auto Ancillary"},
    {"symbol": "AMARARAJA", "name": "Amara Raja Energy & Mobility Ltd", "sector": "Auto Ancillary"},
    {"symbol": "APOLLOTYRE", "name": "Apollo Tyres Ltd", "sector": "Auto Ancillary"},
    {"symbol": "MRF", "name": "MRF Ltd", "sector": "Auto Ancillary"},
    {"symbol": "BALKRISIND", "name": "Balkrishna Industries Ltd", "sector": "Auto Ancillary"},
    # === FMCG ===
    {"symbol": "HINDUNILVR", "name": "Hindustan Unilever Ltd", "sector": "FMCG"},
    {"symbol": "ITC", "name": "ITC Ltd", "sector": "FMCG"},
    {"symbol": "NESTLEIND", "name": "Nestle India Ltd", "sector": "FMCG"},
    {"symbol": "BRITANNIA", "name": "Britannia Industries Ltd", "sector": "FMCG"},
    {"symbol": "DABUR", "name": "Dabur India Ltd", "sector": "FMCG"},
    {"symbol": "MARICO", "name": "Marico Ltd", "sector": "FMCG"},
    {"symbol": "COLPAL", "name": "Colgate-Palmolive (India) Ltd", "sector": "FMCG"},
    {"symbol": "EMAMILTD", "name": "Emami Ltd", "sector": "FMCG"},
    {"symbol": "GODREJCP", "name": "Godrej Consumer Products Ltd", "sector": "FMCG"},
    {"symbol": "TATACONSUM", "name": "Tata Consumer Products Ltd", "sector": "FMCG"},
    {"symbol": "VARUNBEV", "name": "Varun Beverages Ltd", "sector": "FMCG"},
    {"symbol": "RADICO", "name": "Radico Khaitan Ltd", "sector": "FMCG"},
    {"symbol": "UNITDSPR", "name": "United Spirits Ltd", "sector": "FMCG"},
    # === CONSUMER DURABLES ===
    {"symbol": "TITAN", "name": "Titan Company Ltd", "sector": "Consumer"},
    {"symbol": "ASIANPAINT", "name": "Asian Paints Ltd", "sector": "Consumer"},
    {"symbol": "PIDILITIND", "name": "Pidilite Industries Ltd", "sector": "Consumer"},
    {"symbol": "HAVELLS", "name": "Havells India Ltd", "sector": "Consumer"},
    {"symbol": "VOLTAS", "name": "Voltas Ltd", "sector": "Consumer"},
    {"symbol": "BLUESTARCO", "name": "Blue Star Ltd", "sector": "Consumer"},
    {"symbol": "BATAINDIA", "name": "Bata India Ltd", "sector": "Consumer"},
    {"symbol": "PAGEIND", "name": "Page Industries Ltd", "sector": "Consumer"},
    {"symbol": "KALYANKJIL", "name": "Kalyan Jewellers India Ltd", "sector": "Consumer"},
    # === RETAIL ===
    {"symbol": "DMART", "name": "Avenue Supermarts Ltd (D-Mart)", "sector": "Retail"},
    {"symbol": "TRENT", "name": "Trent Ltd", "sector": "Retail"},
    {"symbol": "NYKAA", "name": "FSN E-Commerce Ventures Ltd (Nykaa)", "sector": "Retail"},
    {"symbol": "ZOMATO", "name": "Zomato Ltd", "sector": "Retail"},
    # === METALS & MINING ===
    {"symbol": "TATASTEEL", "name": "Tata Steel Ltd", "sector": "Metal"},
    {"symbol": "JSWSTEEL", "name": "JSW Steel Ltd", "sector": "Metal"},
    {"symbol": "HINDALCO", "name": "Hindalco Industries Ltd", "sector": "Metal"},
    {"symbol": "VEDL", "name": "Vedanta Ltd", "sector": "Metal"},
    {"symbol": "SAIL", "name": "Steel Authority of India Ltd", "sector": "Metal"},
    {"symbol": "NMDC", "name": "NMDC Ltd", "sector": "Metal"},
    {"symbol": "RATNAMANI", "name": "Ratnamani Metals & Tubes Ltd", "sector": "Metal"},
    {"symbol": "JINDALSTEL", "name": "Jindal Steel & Power Ltd", "sector": "Metal"},
    {"symbol": "NATIONALUM", "name": "National Aluminium Co Ltd", "sector": "Metal"},
    {"symbol": "HINDZINC", "name": "Hindustan Zinc Ltd", "sector": "Metal"},
    {"symbol": "COALINDIA", "name": "Coal India Ltd", "sector": "Mining"},
    # === CEMENT ===
    {"symbol": "ULTRACEMCO", "name": "UltraTech Cement Ltd", "sector": "Cement"},
    {"symbol": "SHREECEM", "name": "Shree Cement Ltd", "sector": "Cement"},
    {"symbol": "ACC", "name": "ACC Ltd", "sector": "Cement"},
    {"symbol": "AMBUJACEMENT", "name": "Ambuja Cements Ltd", "sector": "Cement"},
    {"symbol": "RAMCOCEM", "name": "The Ramco Cements Ltd", "sector": "Cement"},
    {"symbol": "JKLAKSHMI", "name": "JK Lakshmi Cement Ltd", "sector": "Cement"},
    {"symbol": "DALMIA", "name": "Dalmia Bharat Ltd", "sector": "Cement"},
    # === INFRASTRUCTURE ===
    {"symbol": "LT", "name": "Larsen & Toubro Ltd", "sector": "Infrastructure"},
    {"symbol": "ADANIPORTS", "name": "Adani Ports & Special Economic Zone Ltd", "sector": "Infrastructure"},
    {"symbol": "IRB", "name": "IRB Infrastructure Developers Ltd", "sector": "Infrastructure"},
    {"symbol": "KNRCON", "name": "KNR Constructions Ltd", "sector": "Infrastructure"},
    {"symbol": "NCC", "name": "NCC Ltd", "sector": "Infrastructure"},
    {"symbol": "PNCINFRA", "name": "PNC Infratech Ltd", "sector": "Infrastructure"},
    {"symbol": "IRCON", "name": "Ircon International Ltd", "sector": "Infrastructure"},
    # === TELECOM ===
    {"symbol": "BHARTIARTL", "name": "Bharti Airtel Ltd", "sector": "Telecom"},
    {"symbol": "TATACOMM", "name": "Tata Communications Ltd", "sector": "Telecom"},
    {"symbol": "IDEA", "name": "Vodafone Idea Ltd", "sector": "Telecom"},
    # === REAL ESTATE ===
    {"symbol": "DLF", "name": "DLF Ltd", "sector": "Real Estate"},
    {"symbol": "GODREJPROP", "name": "Godrej Properties Ltd", "sector": "Real Estate"},
    {"symbol": "OBEROIRLTY", "name": "Oberoi Realty Ltd", "sector": "Real Estate"},
    {"symbol": "PHOENIXLTD", "name": "Phoenix Mills Ltd", "sector": "Real Estate"},
    {"symbol": "SOBHA", "name": "Sobha Ltd", "sector": "Real Estate"},
    {"symbol": "PRESTIGE", "name": "Prestige Estates Projects Ltd", "sector": "Real Estate"},
    {"symbol": "BRIGADE", "name": "Brigade Enterprises Ltd", "sector": "Real Estate"},
    # === CHEMICALS ===
    {"symbol": "SRF", "name": "SRF Ltd", "sector": "Chemicals"},
    {"symbol": "DEEPAKNITRITE", "name": "Deepak Nitrite Ltd", "sector": "Chemicals"},
    {"symbol": "NAVINFLUOR", "name": "Navin Fluorine International Ltd", "sector": "Chemicals"},
    {"symbol": "ASTRAL", "name": "Astral Ltd", "sector": "Chemicals"},
    {"symbol": "FINEORG", "name": "Fine Organic Industries Ltd", "sector": "Chemicals"},
    {"symbol": "ATUL", "name": "Atul Ltd", "sector": "Chemicals"},
    {"symbol": "TATACHEM", "name": "Tata Chemicals Ltd", "sector": "Chemicals"},
    {"symbol": "VINATI", "name": "Vinati Organics Ltd", "sector": "Chemicals"},
    {"symbol": "GALAXYSURF", "name": "Galaxy Surfactants Ltd", "sector": "Chemicals"},
    # === CAPITAL GOODS ===
    {"symbol": "SIEMENS", "name": "Siemens Ltd", "sector": "Capital Goods"},
    {"symbol": "ABB", "name": "ABB India Ltd", "sector": "Capital Goods"},
    {"symbol": "CUMMINSIND", "name": "Cummins India Ltd", "sector": "Capital Goods"},
    {"symbol": "THERMAX", "name": "Thermax Ltd", "sector": "Capital Goods"},
    {"symbol": "BHEL", "name": "Bharat Heavy Electricals Ltd", "sector": "Capital Goods"},
    {"symbol": "BEML", "name": "BEML Ltd", "sector": "Capital Goods"},
    {"symbol": "ELGIEQUIP", "name": "Elgi Equipments Ltd", "sector": "Capital Goods"},
    {"symbol": "AIAENG", "name": "AIA Engineering Ltd", "sector": "Capital Goods"},
    # === DEFENCE ===
    {"symbol": "HAL", "name": "Hindustan Aeronautics Ltd", "sector": "Defence"},
    {"symbol": "BEL", "name": "Bharat Electronics Ltd", "sector": "Defence"},
    {"symbol": "COCHINSHIP", "name": "Cochin Shipyard Ltd", "sector": "Defence"},
    {"symbol": "MAZAGONDOCK", "name": "Mazagon Dock Shipbuilders Ltd", "sector": "Defence"},
    {"symbol": "GRSE", "name": "Garden Reach Shipbuilders & Engineers Ltd", "sector": "Defence"},
    # === HOSPITALITY ===
    {"symbol": "INDHOTEL", "name": "Indian Hotels Co Ltd (Taj)", "sector": "Hospitality"},
    {"symbol": "EIHOTEL", "name": "EIH Ltd (Oberoi Hotels)", "sector": "Hospitality"},
    {"symbol": "LEMONTRE", "name": "Lemon Tree Hotels Ltd", "sector": "Hospitality"},
    {"symbol": "CHALET", "name": "Chalet Hotels Ltd", "sector": "Hospitality"},
    # === MEDIA ===
    {"symbol": "ZEEL", "name": "Zee Entertainment Enterprises Ltd", "sector": "Media"},
    {"symbol": "SUNTV", "name": "Sun TV Network Ltd", "sector": "Media"},
    {"symbol": "PVRINOX", "name": "PVR INOX Ltd", "sector": "Media"},
    {"symbol": "NETWORK18", "name": "Network18 Media & Investments Ltd", "sector": "Media"},
    # === AGRICULTURE ===
    {"symbol": "UPL", "name": "UPL Ltd", "sector": "Agriculture"},
    {"symbol": "PIIND", "name": "PI Industries Ltd", "sector": "Agriculture"},
    {"symbol": "DHANUKA", "name": "Dhanuka Agritech Ltd", "sector": "Agriculture"},
    {"symbol": "COROMANDEL", "name": "Coromandel International Ltd", "sector": "Agriculture"},
    {"symbol": "GNFC", "name": "Gujarat Narmada Valley Fertilizers & Chemicals", "sector": "Agriculture"},
    {"symbol": "CHAMBALFERT", "name": "Chambal Fertilizers & Chemicals Ltd", "sector": "Agriculture"},
    # === LOGISTICS ===
    {"symbol": "DELHIVERY", "name": "Delhivery Ltd", "sector": "Logistics"},
    {"symbol": "BLUEDART", "name": "Blue Dart Express Ltd", "sector": "Logistics"},
    {"symbol": "VRL", "name": "VRL Logistics Ltd", "sector": "Logistics"},
    # === CONGLOMERATE / ADANI ===
    {"symbol": "ADANIENT", "name": "Adani Enterprises Ltd", "sector": "Conglomerate"},
    {"symbol": "ADANIGAS", "name": "Adani Total Gas Ltd", "sector": "Energy"},
    {"symbol": "GRASIM", "name": "Grasim Industries Ltd", "sector": "Diversified"},
    # === PSU / SERVICES ===
    {"symbol": "IRCTC", "name": "Indian Railway Catering and Tourism Corp Ltd", "sector": "Services"},
    {"symbol": "RITES", "name": "RITES Ltd", "sector": "Services"},
    # === FINTECH / NEW AGE ===
    {"symbol": "PAYTM", "name": "One97 Communications Ltd (Paytm)", "sector": "Fintech"},
    {"symbol": "POLICYBZR", "name": "PB Fintech Ltd (PolicyBazaar)", "sector": "Fintech"},
    {"symbol": "JUSTDIAL", "name": "Just Dial Ltd", "sector": "Internet"},
]
